# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "git_statistic",
  "test_exe",
]

resolver = "2"

[workspace.package]
authors = ["liyou"]
description = "Various Tool To Speedup You"
version = "0.0.1"
